In [22]:
!pip install pymysql
!service mysql start

Requirement already satisfied: pymysql in /usr/local/lib/python3.10/dist-packages (1.1.1)
 * Starting MySQL database server mysqld
   ...done.

In [21]:
!mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''"

In [17]:
!mysql  -u root -p '' -e "CREATE DATABASE db_emp"

Enter password:

In [18]:
import pymysql.cursors

db = pymysql.connect(host='127.0.0.1',user="root",password="",database='db_emp',charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)
print("Connection to MySQL database successful!")

Connection to MySQL database successful!